// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	Description string      `json:"description"`
	Done        bool        `json:"done"`
}

type User struct {
	ID       pgtype.UUID `json:"id"`
	OauthID  string      `json:"oauth_id"`
	Username string      `json:"username"`
}
